name: CI

on:
  push:
    branches:
      - main

permissions:
  id-tokens: write
  contents: read

jobs:

  run-terraform:
    name: "Run terraform"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{secrets.aws_region}}
        role-to-assume: ${{secrets.role_to_assume}}

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4
        
    - name: Run terraform init
      run: terraform init

    - name: Run terraform format
      run: terraform fmt -check

    - name: Run terraform plan
      run: terraform plan

    - name: Run terraform apply
      if: github.ref === "refs/head/main" && github.event_name == "push"
      run: terraform apply -auto-approve